@startuml
class AuthenticationService{
login(credential : Credential) : User
register(user : User) : void
}

class CartService{
add(component : PCComponent) : void
remove(component : PCComponent) : void
calculateTotalPrice() : BigDecimal
}

class OrderService{
create(cart : Cart) : void
remove(order : Order) : void
complete(id : int) : void
}

class PCComponentService{
findAllComponents() : List<PCComponent>
findAllGPU() : List<GPU>
findAllCPU() : List<CPU>
findAllCPUCooler() : List<Case>
findAllMotherboard() : List<Case>
findAllPSU() : List<Case>
findAllRAM() : List<Case>
findAllStorage() : List<Case>

}

@enduml